-- AlterTable
ALTER TABLE "RobotSettings" ADD COLUMN IF NOT EXISTS "callOperatorNotifyInbox" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "RobotSettings" ADD COLUMN IF NOT EXISTS "callOperatorNotifyPopup" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "RobotSettings" ADD COLUMN IF NOT EXISTS "callOperatorNotifyEmail" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "RobotSettings" ADD COLUMN IF NOT EXISTS "callOperatorEmail" TEXT NOT NULL DEFAULT '';

ALTER TABLE "OperatorAlert" ADD COLUMN IF NOT EXISTS "inInbox" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "OperatorAlert" ADD COLUMN IF NOT EXISTS "asPopup" BOOLEAN NOT NULL DEFAULT false;
